CREATE TABLE [dbo].[Artists]
(
	[Id]			BIGINT IDENTITY (1,1) CONSTRAINT [PK_Artists] PRIMARY KEY NOT NULL,
	[UniqueId]		UNIQUEIDENTIFIER CONSTRAINT [DF_Artists_UniqueId] DEFAULT (NEWID()) NOT NULL,
	[FirstName]		NVARCHAR(30) NULL,
	[LastName]		NVARCHAR(50) NULL,
	[GroupName]		NVARCHAR(256) NULL,
	[LastUpdate]	DATETIME2 CONSTRAINT [DF_Artists_LastUpdate] DEFAULT (GETDATE()) NOT NULL,
	[CreateDate]	DATETIME2 CONSTRAINT [DF_Artists_CreateDate] DEFAULT (GETDATE()) NOT NULL,
	CONSTRAINT [UK_Artists_UniqueId] UNIQUE ([UniqueId])
)
