CREATE TABLE [dbo].[Spotify]
(
	[Id]			BIGINT IDENTITY (1,1) CONSTRAINT [PK_Spotify] PRIMARY KEY NOT NULL,
	[UniqueId]		UNIQUEIDENTIFIER CONSTRAINT [DF_Spotify_UniqueId] DEFAULT (NEWID()) NOT NULL,
	[SpotifyId]		NVARCHAR(100) NOT NULL,
	[PrewviewUrl]	NVARCHAR(MAX) NOT NULL,
	[ArtSmallUrl]	NVARCHAR(MAX) NULL,
	[ArtMediumUrl]	NVARCHAR(MAX) NULL,
	[ArtLargeUrl]	NVARCHAR(MAX) NULL,
	[LastUpdate]	DATETIME2 CONSTRAINT [DF_Spotify_LastUpdate] DEFAULT (GETDATE()) NOT NULL,
	[CreateDate]	DATETIME2 CONSTRAINT [DF_Spotify_CreateDate] DEFAULT (GETDATE()) NOT NULL,
	CONSTRAINT [UK_Spotify_UniqueId] UNIQUE ([UniqueId])
)
