CREATE TABLE [dbo].[UserRoles]
(
	[Id]			BIGINT IDENTITY (1,1) CONSTRAINT [PK_UserRoles] PRIMARY KEY NOT NULL,
	[UniqueId]		UNIQUEIDENTIFIER CONSTRAINT [DF_UserRoles_UniqueId] DEFAULT (NEWID()) NOT NULL,
	[UserId]		BIGINT NOT NULL,
	[RoleId]		BIGINT NOT NULL,
	[IsActive]		BIT CONSTRAINT [DF_UserRoles] DEFAULT (0) NOT NULL,
	[LastUpdated]	DATETIME2 CONSTRAINT [DF_UserRoles_LastUpdate] DEFAULT (GETDATE()) NOT NULL,
	[CreateDate]	DATETIME2 CONSTRAINT [DF_UserRoles_CreateDate] DEFAULT (GETDATE()) NOT NULL,
	CONSTRAINT [UK_UserRoles_UniqueId]	UNIQUE ([UniqueId]),
	CONSTRAINT [FK_UserRoles_Users]		FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users] ([Id]),
	CONSTRAINT [FK_UserRoles_Roles]		FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Roles] ([Id])
)
