//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADE.NEON.DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeonContext : DbContext
    {
        public NeonContext()
            : base("name=NeonContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<ArtistsTrack> ArtistsTracks { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventStatus> EventStatus1 { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Spotify> Spotifies { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<Workspace> Workspaces { get; set; }
        public virtual DbSet<WorkspaceUser> WorkspaceUsers { get; set; }
        public virtual DbSet<NeonPreviousPassword> NeonPreviousPasswords { get; set; }
        public virtual DbSet<NeonUserClaim> NeonUserClaims { get; set; }
        public virtual DbSet<NeonUserLogin> NeonUserLogins { get; set; }
        public virtual DbSet<NeonRole> NeonRoles { get; set; }
        public virtual DbSet<NeonUserRole> NeonUserRoles { get; set; }
        public virtual DbSet<NeonUser> NeonUsers { get; set; }
        public virtual DbSet<UsersProfile> UsersProfiles { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }
    }
}
