//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADE.NEON.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeonUserClaim
    {
        public int Id { get; set; }
        public System.Guid UniqueId { get; set; }
        public System.Guid UserId { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }
        public Nullable<System.Guid> GuidUser_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual NeonUser NeonUser { get; set; }
    }
}
