//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADE.NEON.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public long Id { get; set; }
        public System.Guid UniqueId { get; set; }
        public long EventId { get; set; }
        public long TrackId { get; set; }
        public bool WasPlayed { get; set; }
        public long Amount { get; set; }
        public bool Archived { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Track Track { get; set; }
    }
}
