//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADE.NEON.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spotify
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spotify()
        {
            this.Tracks = new HashSet<Track>();
        }
    
        public long Id { get; set; }
        public System.Guid UniqueId { get; set; }
        public string SpotifyId { get; set; }
        public string PrewviewUrl { get; set; }
        public string ArtSmallUrl { get; set; }
        public string ArtMediumUrl { get; set; }
        public string ArtLargeUrl { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Track> Tracks { get; set; }
    }
}
