//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADE.NEON.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UsersProfiles = new HashSet<UsersProfile>();
        }
    
        public long Id { get; set; }
        public System.Guid UniqueId { get; set; }
        public long WorkspaceId { get; set; }
        public string UserName { get; set; }
        public string EmailAddress { get; set; }
        public bool ConfirmedEmail { get; set; }
        public string HashedPassword { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Workspace Workspace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersProfile> UsersProfiles { get; set; }
    }
}
